defaults:
  - _self_
  - cluster@_global_: juan_mila.yaml
  - alg: pqn_atari.yaml
# experiment params
NUM_SEEDS: 1
SEED: 0

# if  hyperparameters tuning
HYP_TUNE: False

# debugging
DEBUG: False

# wandb params
RUN_ID: "Test_juan_3"
WANDB_MODE: "online"  # set to online to activate wandb
ENTITY: "puredip"
PROJECT: "Mixture-of-Q-learners"
WANDB_TAGS: ['test',]
alg:
  WANDB_LOG_ALL_SEEDS: False # will log all the vmapped seeds separetely

# where to save the params (if None, will not save)
SAVE_PATH: "./models"
